package com.saed.backend.person;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.saed.backend.context.SaedContext;
import com.saed.backend.context.SaedContextHolder;
import com.saed.backend.person.dto.PersonaRequestDTO;
import com.saed.backend.person.dto.UnitOwnerRequestDTO;
import com.saed.backend.person.dto.UnitResidentRequestDTO;
import com.saed.backend.security.jwt.JwtProvider;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@ActiveProfiles("test")
@AutoConfigureMockMvc
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
public class Phase1DPersonIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JwtProvider jwtProvider;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @org.springframework.boot.test.mock.mockito.MockBean
    private com.saed.backend.authorization.service.AssignmentService assignmentService;

    private static final Long ORG_ADMIN_USER_ID = 888003L;
    private static final Long ORG_ADMIN_ASIGNACION_ID = 888103L;

    @BeforeEach
    public void setupMocks() {
        SaedContextHolder.setContext(SaedContext.builder()
                .userId(1L).organizationId(1L).propertyId(1L)
                .roleCode("SUPERADMIN").roleScope("GLOBAL").build());
        jdbcTemplate.execute("BEGIN PKG_SAED_SESSION.SET_BOOTSTRAP_CONTEXT(1); PKG_SAED_SESSION.SET_CONTEXT(1, 1, 1, 'SUPERADMIN'); END;");
        try { jdbcTemplate.execute("ALTER TABLE PERSONAS MODIFY (ID_PERSONA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))"); } catch (Exception ignored) {}

        try {
            Long rolOrg = jdbcTemplate.queryForObject("SELECT ID_ROL FROM ROLES WHERE CODIGO = 'ADMIN_ORGANIZACION'", Long.class);

            jdbcTemplate.update("MERGE INTO ORGANIZACIONES o USING (SELECT 88801 as id, 'Adv Org 1' as n, 'NIT-88801' as f, 'org1@adv.com' as e FROM DUAL) s " +
                    "ON (o.ID_ORGANIZACION = s.id) WHEN NOT MATCHED THEN INSERT (ID_ORGANIZACION, NOMBRE, IDENTIFICACION_FISCAL, EMAIL_CONTACTO) VALUES (s.id, s.n, s.f, s.e)");

            jdbcTemplate.update("MERGE INTO PERSONAS p USING (SELECT 888003 as id, 1 as td, 'DOC-888003' as nd, 'NATURAL' as tp, 'orgadmin@adv.com' as e, 'Carlos' as pn, 'AdminOrg' as pa FROM DUAL) s " +
                    "ON (p.ID_PERSONA = s.id) WHEN NOT MATCHED THEN INSERT (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, EMAIL, PRIMER_NOMBRE, PRIMER_APELLIDO) VALUES (s.id, s.td, s.nd, s.tp, s.e, s.pn, s.pa)");

            jdbcTemplate.update("MERGE INTO USUARIOS u USING (SELECT 888003 as id, 888003 as p, 'orgadmin_adv' as u, 'orgadmin@adv.com' as e, 'hash' as h, 'ACTIVO' as st FROM DUAL) s " +
                    "ON (u.ID_USUARIO = s.id) WHEN NOT MATCHED THEN INSERT (ID_USUARIO, ID_PERSONA, NOMBRE_USUARIO, EMAIL, HASH_PASSWORD, ESTADO) VALUES (s.id, s.p, s.u, s.e, s.h, s.st)");

            jdbcTemplate.update("MERGE INTO USUARIO_ASIGNACIONES ua USING (SELECT 888103 as id, 888003 as u, " + rolOrg + " as r, 88801 as o, 'ACTIVA' as st FROM DUAL) s " +
                    "ON (ua.ID_ASIGNACION = s.id) WHEN NOT MATCHED THEN INSERT (ID_ASIGNACION, ID_USUARIO, ID_ROL, ID_ORGANIZACION, ESTADO) VALUES (s.id, s.u, s.r, s.o, s.st)");

            jdbcTemplate.execute("COMMIT");
        } catch (Exception ignored) {}

        // Mock ORG_ADMIN with Property
        com.saed.backend.authorization.dto.AssignmentResponseDTO orgDto = new com.saed.backend.authorization.dto.AssignmentResponseDTO();
        orgDto.setIdAsignacion(ORG_ADMIN_ASIGNACION_ID);
        orgDto.setRol(new com.saed.backend.authorization.dto.RoleDTO("ADMIN_ORGANIZACION", "ORGANIZACION"));
        orgDto.setOrganizacion(new com.saed.backend.authorization.dto.OrganizationDTO(88801L, "Adv Org 1"));
        orgDto.setPropiedad(new com.saed.backend.authorization.dto.PropertyDTO(88811L, "Edificio Adv 1"));
        org.mockito.Mockito.when(assignmentService.validateAssignment(ORG_ADMIN_ASIGNACION_ID, ORG_ADMIN_USER_ID))
                .thenReturn(java.util.Optional.of(orgDto));

        jdbcTemplate.execute("BEGIN PKG_SAED_SESSION.CLEAR_CONTEXT; END;");
        SaedContextHolder.clearContext();
    }

    @AfterEach
    public void cleanup() {
        jdbcTemplate.execute("BEGIN PKG_SAED_SESSION.CLEAR_CONTEXT; END;");
        SaedContextHolder.clearContext();
    }

    @Test
    public void testCreatePersona_OrgAdmin_Success() throws Exception {
        String token = jwtProvider.generateIdentityToken(ORG_ADMIN_USER_ID);

        PersonaRequestDTO request = new PersonaRequestDTO(
                1L,
                "DOC-" + UUID.randomUUID().toString().substring(0, 8),
                "NATURAL",
                "Juan",
                "Carlos",
                "Perez",
                "Gomez",
                "juan" + UUID.randomUUID().toString().substring(0, 5) + "@test.com",
                "555123456"
        );

        mockMvc.perform(post("/api/v1/personas")
                .header("Authorization", "Bearer " + token)
                .header("X-Assignment-Id", String.valueOf(ORG_ADMIN_ASIGNACION_ID))
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated());
    }

    @Test
    public void testCreateOwner_InvalidUnit_FailsWithDatabaseErrorOr403() throws Exception {
        String token = jwtProvider.generateIdentityToken(ORG_ADMIN_USER_ID);

        UnitOwnerRequestDTO request = new UnitOwnerRequestDTO(
                1L,
                new BigDecimal("50.00"),
                "S"
        );

        mockMvc.perform(post("/api/v1/units/99999/owners")
                .header("Authorization", "Bearer " + token)
                .header("X-Assignment-Id", String.valueOf(ORG_ADMIN_ASIGNACION_ID))
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(result -> {
                    int status = result.getResponse().getStatus();
                    assertTrue(status == 403 || status == 500);
                });
    }

    @Test
    public void testCreateResident_InvalidUnit_FailsWithDatabaseErrorOr403() throws Exception {
        String token = jwtProvider.generateIdentityToken(ORG_ADMIN_USER_ID);

        UnitResidentRequestDTO request = new UnitResidentRequestDTO(
                1L,
                "ARRENDATARIO"
        );

        mockMvc.perform(post("/api/v1/units/99999/residents")
                .header("Authorization", "Bearer " + token)
                .header("X-Assignment-Id", String.valueOf(ORG_ADMIN_ASIGNACION_ID))
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(result -> {
                    int status = result.getResponse().getStatus();
                    assertTrue(status == 403 || status == 500);
                });
    }

    @Test
    public void testGetPersonas_Success() throws Exception {
        String token = jwtProvider.generateIdentityToken(ORG_ADMIN_USER_ID);

        mockMvc.perform(get("/api/v1/personas?page=0&size=5")
                .header("Authorization", "Bearer " + token)
                .header("X-Assignment-Id", String.valueOf(ORG_ADMIN_ASIGNACION_ID)))
                .andExpect(status().isOk());
    }
}
