-- V4.14: Fix virtual columns that were hardcoded to literal 7
-- CARTERA.SALDO_TOTAL should sum all saldo columns
-- CONCILIACIONES.DIFERENCIA should be SALDO_BANCO - SALDO_LIBROS

-- Fix CARTERA.SALDO_TOTAL virtual column
ALTER TABLE CARTERA DROP COLUMN SALDO_TOTAL;
ALTER TABLE CARTERA ADD SALDO_TOTAL AS (SALDO_CORRIENTE + SALDO_MORA_30 + SALDO_MORA_60 + SALDO_MORA_90_MAS);

-- Fix CONCILIACIONES.DIFERENCIA virtual column
ALTER TABLE CONCILIACIONES DROP COLUMN DIFERENCIA;
ALTER TABLE CONCILIACIONES ADD DIFERENCIA AS (SALDO_BANCO - SALDO_LIBROS);
