-- ============================================================================
-- V5.27: ASIGNACIÓN DE TURNOS DE VIGILANCIA EN PORTERÍAS (LEY 1920 DE 2018)
-- ============================================================================

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(1) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'PORTERIA_TURNOS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE PORTERIA_TURNOS (
                ID_ASIGNACION_TURNO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                ID_PROPIEDAD NUMBER NOT NULL,
                ID_PORTERIA NUMBER NOT NULL,
                ID_USUARIO NUMBER NOT NULL,
                CODIGO_TURNO VARCHAR2(50 CHAR) NOT NULL,
                NOMBRE_TURNO VARCHAR2(100 CHAR),
                HORA_INICIO VARCHAR2(10 CHAR),
                HORA_FIN VARCHAR2(10 CHAR),
                DIAS_SEMANA VARCHAR2(100 CHAR) DEFAULT ''L-D'',
                ESTADO VARCHAR2(20 CHAR) DEFAULT ''ACTIVO'',
                FECHA_ASIGNACION TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_PT_PROPIEDAD FOREIGN KEY (ID_PROPIEDAD) REFERENCES PROPIEDADES(ID_PROPIEDAD) ON DELETE CASCADE,
                CONSTRAINT FK_PT_PORTERIA FOREIGN KEY (ID_PORTERIA) REFERENCES PORTERIAS(ID_PORTERIA) ON DELETE CASCADE,
                CONSTRAINT FK_PT_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
                CONSTRAINT UK_PT_PORTERO_PORTERIA UNIQUE (ID_PORTERIA, ID_USUARIO)
            )
        ';
    END IF;

    -- VPD / RLS Policy
    BEGIN
        DBMS_RLS.ADD_GROUPED_POLICY(
            object_schema   => USER,
            object_name     => 'PORTERIA_TURNOS',
            policy_group    => 'SYS_DEFAULT',
            policy_name     => 'POL_RLS_PROP_PORT_TURNOS',
            function_schema => NULL,
            policy_function => 'PKG_SAED_SECURITY_RLS.FN_FILTRO_PROPIEDAD',
            statement_types => 'SELECT,INSERT,UPDATE,DELETE',
            update_check    => FALSE,
            enable          => TRUE,
            static_policy   => FALSE,
            policy_type     => dbms_rls.DYNAMIC,
            long_predicate  => FALSE
        );
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
END;
/
