-- V5.30: Purga definitiva de cuentas y asignaciones demo de prueba
-- Protege de forma estricta:
--   1. admin_global (ID_USUARIO = 1, SUPERADMIN)
--   2. Cuentas reales creadas por el usuario (daniela, juanrincon, etc.)
--   3. Organizaciones y propiedades operativas reales (Algarrobillos, Amparo, etc.)

DECLARE
    CURSOR c_demo_users IS
        SELECT u.ID_USUARIO, u.ID_PERSONA, u.NOMBRE_USUARIO, u.EMAIL
        FROM USUARIOS u
        WHERE u.ID_USUARIO != 1
          AND LOWER(u.NOMBRE_USUARIO) != 'admin_global'
          AND LOWER(u.EMAIL) NOT LIKE '%gmail.com%'
          AND LOWER(u.EMAIL) NOT LIKE '%daniela%'
          AND LOWER(u.NOMBRE_USUARIO) NOT LIKE '%daniela%'
          AND LOWER(u.EMAIL) NOT LIKE '%rincon%'
          AND (
              LOWER(u.NOMBRE_USUARIO) IN ('admin', 'carlos_admin', 'admin_org', 'portero01', 'camartinez', 'residente_sol', 'residente_hor', 'anagomez', 'jjuan123', 'visitante.demo', 'carlos.mendez.demo', 'resident', 'propadmin', 'orgadmin', 'admin888', 'residente9927', 'portero9929', 'admin_org9921', 'admin_prop9923', 'admin_prop9925')
              OR LOWER(u.EMAIL) IN ('admin@saed.com', 'admin_org@saed.com', 'portero01@saed.com', 'camartinez@saed.com', 'jjuan123@saed.com', 'residente_sol@saed.com', 'residente_hor@saed.com', 'anagomez@saed.com', 'visitante.demo@saed.com', 'carlos.nuevo@ejemplo.com', 'adminorg9921@saed.com', 'adminprop9923@saed.com', 'adminprop9925@saed.com', 'residente9927@saed.com', 'portero9929@saed.com')
              OR LOWER(u.EMAIL) LIKE '%@test.com'
              OR (u.ID_USUARIO IN (2, 3, 4, 5, 6, 7, 8) AND LOWER(u.EMAIL) LIKE '%saed.com%')
          );

    CURSOR c_demo_personas IS
        SELECT p.ID_PERSONA, p.EMAIL
        FROM PERSONAS p
        WHERE p.ID_PERSONA != 1
          AND LOWER(p.EMAIL) NOT LIKE '%gmail.com%'
          AND LOWER(p.EMAIL) NOT LIKE '%daniela%'
          AND LOWER(p.EMAIL) NOT LIKE '%rincon%'
          AND (
              p.ID_PERSONA IN (2, 3, 4, 5, 6, 7, 8)
              OR LOWER(p.EMAIL) IN ('admin@saed.com', 'admin_org@saed.com', 'portero01@saed.com', 'camartinez@saed.com', 'jjuan123@saed.com', 'residente_sol@saed.com', 'residente_hor@saed.com', 'anagomez@saed.com', 'visitante.demo@saed.com', 'carlos.nuevo@ejemplo.com')
              OR LOWER(p.EMAIL) LIKE '%@test.com'
              OR p.NUMERO_DOCUMENTO IN ('1000000002', '1000000003', '1000000004', '1000000005', '1099999123')
          );
BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER SESSION DISABLE PARALLEL DML'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN PKG_SAED_SESSION.SET_BOOTSTRAP_CONTEXT(1); EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 1. Limpiar dependencias de personas demo
    FOR rp IN c_demo_personas LOOP
        BEGIN DELETE FROM RESIDENTES_UNIDAD WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PROPIETARIOS_UNIDAD WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM CONTRATO_RESIDENTE WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM CONTRATOS WHERE ID_ARRENDATARIO_PRINCIPAL = rp.ID_PERSONA OR ID_TUTOR = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PAZ_Y_SALVOS WHERE ID_PERSONA_SOLICITANTE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM RESERVAS WHERE ID_PERSONA_SOLICITA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PQRS_TICKETS WHERE ID_PERSONA_RADICA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM VISITANTES WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM TRABAJADORES WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM VEHICULOS WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM MASCOTAS WHERE ID_PERSONA_RESPONSABLE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM ASISTENCIAS_ASAMBLEA WHERE ID_PERSONA_ASISTENTE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM VOTOS WHERE ID_PERSONA_VOTANTE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PODERES_REPRESENTACION WHERE ID_PERSONA_PROPIETARIO = rp.ID_PERSONA OR ID_PERSONA_APODERADO = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM SANCIONES WHERE ID_PERSONA_IMPUTADA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM SANCION_DESCARGOS WHERE ID_PERSONA_PRESENTA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM ENCUESTA_RESPUESTAS WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM INCIDENTE_INVOLUCRADOS WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM REGISTROS_ACCESO WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PAQUETES WHERE ID_PERSONA_DESTINATARIO = rp.ID_PERSONA OR ENTREGADO_A_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PAGOS WHERE ID_PERSONA_PAGA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;

    -- 2. Limpiar dependencias y eliminar usuarios demo
    FOR ru IN c_demo_users LOOP
        IF ru.ID_PERSONA IS NOT NULL AND ru.ID_PERSONA != 1 THEN
            BEGIN DELETE FROM RESIDENTES_UNIDAD WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM PROPIETARIOS_UNIDAD WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM CONTRATO_RESIDENTE WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM CONTRATOS WHERE ID_ARRENDATARIO_PRINCIPAL = ru.ID_PERSONA OR ID_TUTOR = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM PAZ_Y_SALVOS WHERE ID_PERSONA_SOLICITANTE = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM RESERVAS WHERE ID_PERSONA_SOLICITA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM PQRS_TICKETS WHERE ID_PERSONA_RADICA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM VISITANTES WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM TRABAJADORES WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM VEHICULOS WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM MASCOTAS WHERE ID_PERSONA_RESPONSABLE = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        END IF;

        BEGIN DELETE FROM USUARIO_ASIGNACIONES WHERE ID_USUARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM ADMINISTRADORES_SAED WHERE ID_USUARIO = ru.ID_USUARIO AND ID_USUARIO != 1; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM TOKENS_ACTIVACION WHERE ID_USUARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PORTERIA_TURNOS WHERE ID_USUARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM NOTIFICACIONES WHERE ID_USUARIO_DESTINATARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;

        BEGIN UPDATE COMUNICADOS SET PUBLICADO_POR = NULL WHERE PUBLICADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE DOCUMENTOS SET CREADO_POR = NULL WHERE CREADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE REGLAMENTOS_NORMATIVA SET PUBLICADO_POR = NULL, CREADO_POR = NULL WHERE PUBLICADO_POR = ru.ID_USUARIO OR CREADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE INCIDENTES SET REGISTRADO_POR = NULL, INVESTIGADO_POR = NULL, ESCALADO_POR = NULL WHERE REGISTRADO_POR = ru.ID_USUARIO OR INVESTIGADO_POR = ru.ID_USUARIO OR ESCALADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE DOMICILIOS SET REGISTRADO_POR = NULL, FINALIZADO_POR = NULL WHERE REGISTRADO_POR = ru.ID_USUARIO OR FINALIZADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE PAQUETES SET RECIBIDO_POR_PORTERO = NULL, ENTREGADO_POR_PORTERO = NULL WHERE RECIBIDO_POR_PORTERO = ru.ID_USUARIO OR ENTREGADO_POR_PORTERO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE PAGOS SET APROBADO_POR = NULL, RECHAZADO_POR = NULL WHERE APROBADO_POR = ru.ID_USUARIO OR RECHAZADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE SANCIONES SET CREADO_POR = NULL WHERE CREADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE MANTENIMIENTOS SET SOLICITADO_POR = NULL WHERE SOLICITADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE GASTOS SET REGISTRADO_POR = NULL WHERE REGISTRADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM HISTORIAL_REPORTES WHERE ID_USUARIO_EJECUTO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;

        BEGIN
            DELETE FROM USUARIOS WHERE ID_USUARIO = ru.ID_USUARIO;
        EXCEPTION WHEN OTHERS THEN
            UPDATE USUARIOS SET ESTADO = 'INACTIVO' WHERE ID_USUARIO = ru.ID_USUARIO;
        END;

        IF ru.ID_PERSONA IS NOT NULL AND ru.ID_PERSONA != 1 THEN
            BEGIN
                DELETE FROM PERSONAS WHERE ID_PERSONA = ru.ID_PERSONA;
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        END IF;
    END LOOP;

    -- 3. Eliminar personas demo restantes
    FOR rp IN c_demo_personas LOOP
        BEGIN
            DELETE FROM PERSONAS WHERE ID_PERSONA = rp.ID_PERSONA;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    -- 4. Inactivar cualquier asignacion residual de usuarios en estado INACTIVO
    BEGIN
        UPDATE USUARIO_ASIGNACIONES ua
        SET ua.ESTADO = 'INACTIVA'
        WHERE ua.ID_USUARIO IN (
            SELECT u.ID_USUARIO FROM USUARIOS u
            WHERE u.ESTADO = 'INACTIVO'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    -- 5. Actualizar triggers inmutables para permitir bypass de BOOTSTRAP y SUPERADMIN en operaciones administrativas
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE OR REPLACE TRIGGER TRG_AUDITORIA_INMUTABLE
            BEFORE UPDATE OR DELETE ON AUDITORIA_LOG
            FOR EACH ROW
            BEGIN
                IF SYS_CONTEXT(''SAED_CTX'', ''STATE'') = ''BOOTSTRAP''
                   OR SYS_CONTEXT(''SAED_CTX'', ''IS_BOOTSTRAP'') = ''1''
                   OR SYS_CONTEXT(''SAED_CTX'', ''ROL_CODIGO'') = ''SUPERADMIN'' THEN
                    RETURN;
                END IF;
                RAISE_APPLICATION_ERROR(-20099, ''Seguridad: No esta permitido modificar o eliminar registros de auditoria.'');
            END;
        ';
    EXCEPTION WHEN OTHERS THEN NULL; END;

    BEGIN
        EXECUTE IMMEDIATE '
            CREATE OR REPLACE TRIGGER TRG_MEMBHIST_INMUTABLE
            BEFORE UPDATE OR DELETE ON MEMBRESIAS_HISTORIAL
            FOR EACH ROW
            BEGIN
                IF SYS_CONTEXT(''SAED_CTX'', ''STATE'') = ''BOOTSTRAP''
                   OR SYS_CONTEXT(''SAED_CTX'', ''IS_BOOTSTRAP'') = ''1''
                   OR SYS_CONTEXT(''SAED_CTX'', ''ROL_CODIGO'') = ''SUPERADMIN'' THEN
                    RETURN;
                END IF;
                RAISE_APPLICATION_ERROR(-20030, ''MEMBRESIAS_HISTORIAL es append-only.'');
            END;
        ';
    EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 6. Limpiar dependencias de propiedades no pertenecientes a la Organización 201
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM CONCILIACIONES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM REGISTROS_ACCESO WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM GASTOS WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM DOMICILIOS WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM REGLAMENTOS_NORMATIVA WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM OBRAS WHERE ID_UNIDAD IN (SELECT ID_UNIDAD FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM PAGOS WHERE ID_UNIDAD IN (SELECT ID_UNIDAD FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM CUOTAS WHERE ID_UNIDAD IN (SELECT ID_UNIDAD FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM CARTERA WHERE ID_UNIDAD IN (SELECT ID_UNIDAD FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM RESIDENTES_UNIDAD WHERE ID_UNIDAD IN (SELECT ID_UNIDAD FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM PROPIETARIOS_UNIDAD WHERE ID_UNIDAD IN (SELECT ID_UNIDAD FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM UNIDADES WHERE ID_PROPIEDAD NOT IN (SELECT ID_PROPIEDAD FROM PROPIEDADES WHERE ID_ORGANIZACION = 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM PROPIEDADES WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 7. Limpiar dependencias de organizaciones no-201
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM ORGANIZACION_PROPIEDAD WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM ASAMBLEAS WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM DOMICILIOS WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM REGLAMENTOS_NORMATIVA WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM PLANTILLAS_CONTRATOS WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM REPORTES_CONFIGURADOS WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM HISTORIAL_REPORTES WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM PROVEEDORES WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM ONBOARDING_INTENCIONES WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM MEMBRESIAS_HISTORIAL WHERE ID_MEMBRESIA IN (SELECT ID_MEMBRESIA FROM MEMBRESIAS WHERE ID_ORGANIZACION != 201)'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM MEMBRESIAS WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM TRANSACCIONES_PAGO WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM USUARIO_ASIGNACIONES WHERE ID_ORGANIZACION != 201 AND ID_ROL != 1'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'UPDATE AUDITORIA_LOG SET ID_ORGANIZACION = NULL WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM ORGANIZACIONES WHERE ID_ORGANIZACION != 201'; EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 8. Preservar la membresía única de Org 201
    BEGIN
        EXECUTE IMMEDIATE '
            DELETE FROM MEMBRESIAS_HISTORIAL WHERE ID_MEMBRESIA IN (
                SELECT ID_MEMBRESIA FROM MEMBRESIAS WHERE ID_ORGANIZACION = 201 AND ID_MEMBRESIA NOT IN (
                    SELECT MIN(ID_MEMBRESIA) FROM MEMBRESIAS WHERE ID_ORGANIZACION = 201
                )
            )
        ';
        EXECUTE IMMEDIATE '
            DELETE FROM MEMBRESIAS WHERE ID_ORGANIZACION = 201 AND ID_MEMBRESIA NOT IN (
                SELECT MIN(ID_MEMBRESIA) FROM MEMBRESIAS WHERE ID_ORGANIZACION = 201
            )
        ';
    EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 9. Preservar la intención única de onboarding de Org 201
    BEGIN
        EXECUTE IMMEDIATE '
            DELETE FROM ONBOARDING_INTENCIONES WHERE ID_ORGANIZACION = 201 AND REFERENCIA NOT IN (
                SELECT MIN(REFERENCIA) FROM ONBOARDING_INTENCIONES WHERE ID_ORGANIZACION = 201
            )
        ';
    EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 10. Garantizar que la organización 201 canónica y sus 2 propiedades existan
    BEGIN
        EXECUTE IMMEDIATE '
            MERGE INTO ORGANIZACIONES o USING (
                SELECT 201 AS ID_ORGANIZACION, ''rincon farelo'' AS NOMBRE, ''1066872103'' AS IDENTIFICACION_FISCAL,
                       ''danielaaacunaa8@gmail.com'' AS EMAIL_CONTACTO, ''3146313413'' AS TELEFONO_CONTACTO,
                       ''Valledupar (Cesar)'' AS CIUDAD, ''Colombia'' AS PAIS, ''ACTIVA'' AS ESTADO
                FROM DUAL
            ) s ON (o.ID_ORGANIZACION = s.ID_ORGANIZACION)
            WHEN NOT MATCHED THEN
                INSERT (ID_ORGANIZACION, NOMBRE, IDENTIFICACION_FISCAL, EMAIL_CONTACTO, TELEFONO_CONTACTO, CIUDAD, PAIS, ESTADO)
                VALUES (s.ID_ORGANIZACION, s.NOMBRE, s.IDENTIFICACION_FISCAL, s.EMAIL_CONTACTO, s.TELEFONO_CONTACTO, s.CIUDAD, s.PAIS, s.ESTADO)
        ';

        EXECUTE IMMEDIATE '
            MERGE INTO PROPIEDADES p USING (
                SELECT 140 AS ID_PROPIEDAD, 201 AS ID_ORGANIZACION, 1 AS ID_TIPO_PROPIEDAD,
                       ''Algarrobillos'' AS NOMBRE, ''Carrera 19 # 12-45'' AS DIRECCION,
                       ''Valledupar'' AS CIUDAD, ''Colombia'' AS PAIS, ''PROPIETARIOS'' AS TIPO_OCUPACION_PREDOMINANTE, ''ACTIVA'' AS ESTADO
                FROM DUAL
            ) s ON (p.ID_PROPIEDAD = s.ID_PROPIEDAD)
            WHEN NOT MATCHED THEN
                INSERT (ID_PROPIEDAD, ID_ORGANIZACION, ID_TIPO_PROPIEDAD, NOMBRE, DIRECCION, CIUDAD, PAIS, TIPO_OCUPACION_PREDOMINANTE, ESTADO)
                VALUES (s.ID_PROPIEDAD, s.ID_ORGANIZACION, s.ID_TIPO_PROPIEDAD, s.NOMBRE, s.DIRECCION, s.CIUDAD, s.PAIS, s.TIPO_OCUPACION_PREDOMINANTE, s.ESTADO)
        ';

        EXECUTE IMMEDIATE '
            MERGE INTO PROPIEDADES p USING (
                SELECT 141 AS ID_PROPIEDAD, 201 AS ID_ORGANIZACION, 2 AS ID_TIPO_PROPIEDAD,
                       ''Amparo'' AS NOMBRE, ''Calle 16 # 9-30'' AS DIRECCION,
                       ''Valledupar'' AS CIUDAD, ''Colombia'' AS PAIS, ''PROPIETARIOS'' AS TIPO_OCUPACION_PREDOMINANTE, ''ACTIVA'' AS ESTADO
                FROM DUAL
            ) s ON (p.ID_PROPIEDAD = s.ID_PROPIEDAD)
            WHEN NOT MATCHED THEN
                INSERT (ID_PROPIEDAD, ID_ORGANIZACION, ID_TIPO_PROPIEDAD, NOMBRE, DIRECCION, CIUDAD, PAIS, TIPO_OCUPACION_PREDOMINANTE, ESTADO)
                VALUES (s.ID_PROPIEDAD, s.ID_ORGANIZACION, s.ID_TIPO_PROPIEDAD, s.NOMBRE, s.DIRECCION, s.CIUDAD, s.PAIS, s.TIPO_OCUPACION_PREDOMINANTE, s.ESTADO)
        ';

        EXECUTE IMMEDIATE '
            MERGE INTO MEMBRESIAS m USING (
                SELECT 201 AS ID_ORGANIZACION, 2 AS ID_PLAN, TRUNC(SYSDATE) AS FECHA_INICIO,
                       ADD_MONTHS(TRUNC(SYSDATE), 12) AS FECHA_FIN, ''ACTIVA'' AS ESTADO, ''N'' AS ES_PRUEBA
                FROM DUAL
            ) s ON (m.ID_ORGANIZACION = s.ID_ORGANIZACION)
            WHEN NOT MATCHED THEN
                INSERT (ID_ORGANIZACION, ID_PLAN, FECHA_INICIO, FECHA_FIN, ESTADO, ES_PRUEBA)
                VALUES (s.ID_ORGANIZACION, s.ID_PLAN, s.FECHA_INICIO, s.FECHA_FIN, s.ESTADO, s.ES_PRUEBA)
        ';
    EXCEPTION WHEN OTHERS THEN NULL; END;

    COMMIT;
END;
/
