-- V5.30: Purga definitiva de cuentas y asignaciones demo de prueba
-- Protege de forma estricta:
--   1. admin_global (ID_USUARIO = 1, SUPERADMIN)
--   2. Cuentas reales creadas por el usuario (daniela, juanrincon, etc.)
--   3. Organizaciones y propiedades operativas reales (Algarrobillos, Amparo, etc.)

DECLARE
    CURSOR c_demo_users IS
        SELECT u.ID_USUARIO, u.ID_PERSONA, u.NOMBRE_USUARIO, u.EMAIL
        FROM USUARIOS u
        WHERE u.ID_USUARIO != 1
          AND LOWER(u.NOMBRE_USUARIO) != 'admin_global'
          AND LOWER(u.EMAIL) NOT LIKE '%gmail.com%'
          AND LOWER(u.EMAIL) NOT LIKE '%daniela%'
          AND LOWER(u.NOMBRE_USUARIO) NOT LIKE '%daniela%'
          AND LOWER(u.EMAIL) NOT LIKE '%rincon%'
          AND (
              LOWER(u.NOMBRE_USUARIO) IN ('admin', 'carlos_admin', 'admin_org', 'portero01', 'camartinez', 'residente_sol', 'residente_hor', 'anagomez', 'jjuan123', 'visitante.demo', 'carlos.mendez.demo', 'resident', 'propadmin', 'orgadmin', 'admin888', 'residente9927', 'portero9929', 'admin_org9921', 'admin_prop9923', 'admin_prop9925')
              OR LOWER(u.EMAIL) IN ('admin@saed.com', 'admin_org@saed.com', 'portero01@saed.com', 'camartinez@saed.com', 'jjuan123@saed.com', 'residente_sol@saed.com', 'residente_hor@saed.com', 'anagomez@saed.com', 'visitante.demo@saed.com', 'carlos.nuevo@ejemplo.com', 'adminorg9921@saed.com', 'adminprop9923@saed.com', 'adminprop9925@saed.com', 'residente9927@saed.com', 'portero9929@saed.com')
              OR LOWER(u.EMAIL) LIKE '%@test.com'
              OR (u.ID_USUARIO IN (2, 3, 4, 5, 6, 7, 8) AND LOWER(u.EMAIL) LIKE '%saed.com%')
          );

    CURSOR c_demo_personas IS
        SELECT p.ID_PERSONA, p.EMAIL
        FROM PERSONAS p
        WHERE p.ID_PERSONA != 1
          AND LOWER(p.EMAIL) NOT LIKE '%gmail.com%'
          AND LOWER(p.EMAIL) NOT LIKE '%daniela%'
          AND LOWER(p.EMAIL) NOT LIKE '%rincon%'
          AND (
              p.ID_PERSONA IN (2, 3, 4, 5, 6, 7, 8)
              OR LOWER(p.EMAIL) IN ('admin@saed.com', 'admin_org@saed.com', 'portero01@saed.com', 'camartinez@saed.com', 'jjuan123@saed.com', 'residente_sol@saed.com', 'residente_hor@saed.com', 'anagomez@saed.com', 'visitante.demo@saed.com', 'carlos.nuevo@ejemplo.com')
              OR LOWER(p.EMAIL) LIKE '%@test.com'
              OR p.NUMERO_DOCUMENTO IN ('1000000002', '1000000003', '1000000004', '1000000005', '1099999123')
          );
BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER SESSION DISABLE PARALLEL DML'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN PKG_SAED_SESSION.SET_BOOTSTRAP_CONTEXT(1); EXCEPTION WHEN OTHERS THEN NULL; END;

    -- 1. Limpiar dependencias de personas demo
    FOR rp IN c_demo_personas LOOP
        BEGIN DELETE FROM RESIDENTES_UNIDAD WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PROPIETARIOS_UNIDAD WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM CONTRATO_RESIDENTE WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM CONTRATOS WHERE ID_ARRENDATARIO_PRINCIPAL = rp.ID_PERSONA OR ID_TUTOR = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PAZ_Y_SALVOS WHERE ID_PERSONA_SOLICITANTE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM RESERVAS WHERE ID_PERSONA_SOLICITA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PQRS_TICKETS WHERE ID_PERSONA_RADICA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM VISITANTES WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM TRABAJADORES WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM VEHICULOS WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM MASCOTAS WHERE ID_PERSONA_RESPONSABLE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM ASISTENCIAS_ASAMBLEA WHERE ID_PERSONA_ASISTENTE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM VOTOS WHERE ID_PERSONA_VOTANTE = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PODERES_REPRESENTACION WHERE ID_PERSONA_PROPIETARIO = rp.ID_PERSONA OR ID_PERSONA_APODERADO = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM SANCIONES WHERE ID_PERSONA_IMPUTADA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM SANCION_DESCARGOS WHERE ID_PERSONA_PRESENTA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM ENCUESTA_RESPUESTAS WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM INCIDENTE_INVOLUCRADOS WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM REGISTROS_ACCESO WHERE ID_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PAQUETES WHERE ID_PERSONA_DESTINATARIO = rp.ID_PERSONA OR ENTREGADO_A_PERSONA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PAGOS WHERE ID_PERSONA_PAGA = rp.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;

    -- 2. Limpiar dependencias y eliminar usuarios demo
    FOR ru IN c_demo_users LOOP
        IF ru.ID_PERSONA IS NOT NULL AND ru.ID_PERSONA != 1 THEN
            BEGIN DELETE FROM RESIDENTES_UNIDAD WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM PROPIETARIOS_UNIDAD WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM CONTRATO_RESIDENTE WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM CONTRATOS WHERE ID_ARRENDATARIO_PRINCIPAL = ru.ID_PERSONA OR ID_TUTOR = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM PAZ_Y_SALVOS WHERE ID_PERSONA_SOLICITANTE = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM RESERVAS WHERE ID_PERSONA_SOLICITA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM PQRS_TICKETS WHERE ID_PERSONA_RADICA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM VISITANTES WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM TRABAJADORES WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM VEHICULOS WHERE ID_PERSONA = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
            BEGIN DELETE FROM MASCOTAS WHERE ID_PERSONA_RESPONSABLE = ru.ID_PERSONA; EXCEPTION WHEN OTHERS THEN NULL; END;
        END IF;

        BEGIN DELETE FROM USUARIO_ASIGNACIONES WHERE ID_USUARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM ADMINISTRADORES_SAED WHERE ID_USUARIO = ru.ID_USUARIO AND ID_USUARIO != 1; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM TOKENS_ACTIVACION WHERE ID_USUARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM PORTERIA_TURNOS WHERE ID_USUARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM NOTIFICACIONES WHERE ID_USUARIO_DESTINATARIO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;

        BEGIN UPDATE COMUNICADOS SET PUBLICADO_POR = NULL WHERE PUBLICADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE DOCUMENTOS SET CREADO_POR = NULL WHERE CREADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE REGLAMENTOS_NORMATIVA SET PUBLICADO_POR = NULL, CREADO_POR = NULL WHERE PUBLICADO_POR = ru.ID_USUARIO OR CREADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE INCIDENTES SET REGISTRADO_POR = NULL, INVESTIGADO_POR = NULL, ESCALADO_POR = NULL WHERE REGISTRADO_POR = ru.ID_USUARIO OR INVESTIGADO_POR = ru.ID_USUARIO OR ESCALADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE DOMICILIOS SET REGISTRADO_POR = NULL, FINALIZADO_POR = NULL WHERE REGISTRADO_POR = ru.ID_USUARIO OR FINALIZADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE PAQUETES SET RECIBIDO_POR_PORTERO = NULL, ENTREGADO_POR_PORTERO = NULL WHERE RECIBIDO_POR_PORTERO = ru.ID_USUARIO OR ENTREGADO_POR_PORTERO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE PAGOS SET APROBADO_POR = NULL, RECHAZADO_POR = NULL WHERE APROBADO_POR = ru.ID_USUARIO OR RECHAZADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE SANCIONES SET CREADO_POR = NULL WHERE CREADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE MANTENIMIENTOS SET SOLICITADO_POR = NULL WHERE SOLICITADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN UPDATE GASTOS SET REGISTRADO_POR = NULL WHERE REGISTRADO_POR = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;
        BEGIN DELETE FROM HISTORIAL_REPORTES WHERE ID_USUARIO_EJECUTO = ru.ID_USUARIO; EXCEPTION WHEN OTHERS THEN NULL; END;

        BEGIN
            DELETE FROM USUARIOS WHERE ID_USUARIO = ru.ID_USUARIO;
        EXCEPTION WHEN OTHERS THEN
            UPDATE USUARIOS SET ESTADO = 'INACTIVO' WHERE ID_USUARIO = ru.ID_USUARIO;
        END;

        IF ru.ID_PERSONA IS NOT NULL AND ru.ID_PERSONA != 1 THEN
            BEGIN
                DELETE FROM PERSONAS WHERE ID_PERSONA = ru.ID_PERSONA;
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        END IF;
    END LOOP;

    -- 3. Eliminar personas demo restantes
    FOR rp IN c_demo_personas LOOP
        BEGIN
            DELETE FROM PERSONAS WHERE ID_PERSONA = rp.ID_PERSONA;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    -- 4. Inactivar cualquier asignacion residual de usuarios en estado INACTIVO
    BEGIN
        UPDATE USUARIO_ASIGNACIONES ua
        SET ua.ESTADO = 'INACTIVA'
        WHERE ua.ID_USUARIO IN (
            SELECT u.ID_USUARIO FROM USUARIOS u
            WHERE u.ESTADO = 'INACTIVO'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    COMMIT;
END;
/
