-- Migración V5.4: Permitir fotos base64 en FOTO_PAQUETE_URL y FOTO_COMPROBANTE_URL
-- Solución para ORA-12899 en registro de paquetes y comprobantes de entrega (usando columnas temporales para evitar ORA-22858)

DECLARE
    v_type VARCHAR2(30);
BEGIN
    SELECT DATA_TYPE INTO v_type FROM USER_TAB_COLS WHERE TABLE_NAME = 'PAQUETES' AND COLUMN_NAME = 'FOTO_PAQUETE_URL';
    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES ADD (FOTO_PAQUETE_URL_CLOB CLOB)';
        EXECUTE IMMEDIATE 'UPDATE PAQUETES SET FOTO_PAQUETE_URL_CLOB = FOTO_PAQUETE_URL';
        EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES DROP COLUMN FOTO_PAQUETE_URL';
        EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES RENAME COLUMN FOTO_PAQUETE_URL_CLOB TO FOTO_PAQUETE_URL';
    END IF;

    SELECT DATA_TYPE INTO v_type FROM USER_TAB_COLS WHERE TABLE_NAME = 'PAQUETES' AND COLUMN_NAME = 'FOTO_COMPROBANTE_URL';
    IF v_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES ADD (FOTO_COMPROBANTE_URL_CLOB CLOB)';
        EXECUTE IMMEDIATE 'UPDATE PAQUETES SET FOTO_COMPROBANTE_URL_CLOB = FOTO_COMPROBANTE_URL';
        EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES DROP COLUMN FOTO_COMPROBANTE_URL';
        EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES RENAME COLUMN FOTO_COMPROBANTE_URL_CLOB TO FOTO_COMPROBANTE_URL';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

COMMIT;
