-- ==============================================================================
-- SAED 2.0 — DEMO DATASET SEED SCRIPT (MVP-03)
-- File: database/demo/V5.99__demo_seeds.sql
-- Description: Idempotent and reproducible seed script for functional demonstrations.
-- Compatible with: Oracle Database 18c XE / Oracle Cloud ATP 19c (Read-Only target in local XE)
-- Design: Uses canonical INSERT ... WHERE NOT EXISTS + UPDATE pattern to avoid ORA-28132 (VPD MERGE limitation)
-- Scope:
--   - 1 Organization (SAED Global S.A.S.)
--   - 1 Property (Edificio Residencial SAED)
--   - 4 Units (Apto 101, Apto 102, Apto 201, Apto 202)
--   - 1 SUPERADMIN (admin_global)
--   - 1 ADMIN_PROPIEDAD (admin)
--   - 1 PORTERO (portero01)
--   - 2 RESIDENTES (camartinez in Apto 101, anagomez in Apto 102)
--   - 1 VISITANTE (visitante.demo)
--   - 1 Scheduled Visit with active QR Access
--   - Parking spots & 1 visitor vehicle inside
--   - Financial ledger: 1 paid cuota + payment, 1 pending cuota for coherent dashboard
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 0. Set Zero-Trust Bootstrap & SuperAdmin Context to bypass RLS during seeding
-- ------------------------------------------------------------------------------
BEGIN
    PKG_SAED_SESSION.SET_BOOTSTRAP_CONTEXT(1);
    PKG_SAED_SESSION.SET_CONTEXT(1, 1, 1, 'SUPERADMIN');
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- ------------------------------------------------------------------------------
-- 1. Base Catalogs (Tipos Documento, Tipos Propiedad, Tipos Unidad, Roles)
-- ------------------------------------------------------------------------------
INSERT INTO TIPOS_DOCUMENTO (ID_TIPO_DOCUMENTO, CODIGO, NOMBRE, APLICA_PERSONA_NATURAL, APLICA_PERSONA_JURIDICA, ESTADO)
SELECT 1, 'CC', 'Cedula de Ciudadania', 'S', 'N', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TIPOS_DOCUMENTO WHERE CODIGO = 'CC');

INSERT INTO TIPOS_PROPIEDAD (ID_TIPO_PROPIEDAD, CODIGO, NOMBRE)
SELECT 1, 'EDIFICIO', 'Edificio Residencial' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TIPOS_PROPIEDAD WHERE CODIGO = 'EDIFICIO');

INSERT INTO TIPOS_UNIDAD (ID_TIPO_UNIDAD, CODIGO, NOMBRE)
SELECT 1, 'APARTAMENTO', 'Apartamento' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TIPOS_UNIDAD WHERE CODIGO = 'APARTAMENTO');

INSERT INTO ROLES (ID_ROL, CODIGO, NOMBRE, ALCANCE, ESTADO)
SELECT 1, 'SUPERADMIN', 'Super Administrador', 'GLOBAL', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE CODIGO = 'SUPERADMIN');

INSERT INTO ROLES (ID_ROL, CODIGO, NOMBRE, ALCANCE, ESTADO)
SELECT 2, 'ADMIN_ORGANIZACION', 'Admin Organizacion', 'ORGANIZACION', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE CODIGO = 'ADMIN_ORGANIZACION');

INSERT INTO ROLES (ID_ROL, CODIGO, NOMBRE, ALCANCE, ESTADO)
SELECT 3, 'ADMIN_PROPIEDAD', 'Admin Propiedad', 'PROPIEDAD', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE CODIGO = 'ADMIN_PROPIEDAD');

INSERT INTO ROLES (ID_ROL, CODIGO, NOMBRE, ALCANCE, ESTADO)
SELECT 4, 'PORTERO', 'Portero / Vigilante', 'PROPIEDAD', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE CODIGO = 'PORTERO');

INSERT INTO ROLES (ID_ROL, CODIGO, NOMBRE, ALCANCE, ESTADO)
SELECT 5, 'RESIDENTE', 'Residente', 'UNIDAD', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE CODIGO = 'RESIDENTE');

-- ------------------------------------------------------------------------------
-- 2. Organization (SAED Global S.A.S.)
-- ------------------------------------------------------------------------------
INSERT INTO ORGANIZACIONES (ID_ORGANIZACION, NOMBRE, IDENTIFICACION_FISCAL, EMAIL_CONTACTO, TELEFONO_CONTACTO, DIRECCION, CIUDAD, PAIS, ESTADO)
SELECT 1, 'SAED Global S.A.S.', '900123456-1', 'contacto@saed.com', '+57 300 123 4567', 'Calle 100 # 15-20', 'Bogota', 'Colombia', 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ORGANIZACIONES WHERE ID_ORGANIZACION = 1);

UPDATE ORGANIZACIONES SET NOMBRE = 'SAED Global S.A.S.', EMAIL_CONTACTO = 'contacto@saed.com', ESTADO = 'ACTIVA' WHERE ID_ORGANIZACION = 1;

-- ------------------------------------------------------------------------------
-- 3. Property (Edificio Residencial SAED)
-- ------------------------------------------------------------------------------
INSERT INTO PROPIEDADES (ID_PROPIEDAD, ID_ORGANIZACION, ID_TIPO_PROPIEDAD, NOMBRE, DIRECCION, CIUDAD, PAIS, TIPO_OCUPACION_PREDOMINANTE, ESTADO)
SELECT 1, 1, 1, 'Edificio Residencial SAED', 'Calle 100 # 15-20', 'Bogota', 'Colombia', 'MIXTA', 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PROPIEDADES WHERE ID_PROPIEDAD = 1);

UPDATE PROPIEDADES SET NOMBRE = 'Edificio Residencial SAED', DIRECCION = 'Calle 100 # 15-20', ESTADO = 'ACTIVA' WHERE ID_PROPIEDAD = 1;

-- ------------------------------------------------------------------------------
-- 3b. Porterías (Punto de control y recepción)
-- ------------------------------------------------------------------------------
INSERT INTO PORTERIAS (ID_PORTERIA, ID_PROPIEDAD, NOMBRE, UBICACION, TELEFONO_CONTACTO, ESTADO)
SELECT 1, 1, 'Portería Principal', 'Entrada Principal Torre 1', '+57 300 123 4567', 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PORTERIAS WHERE ID_PORTERIA = 1 OR (ID_PROPIEDAD = 1 AND UPPER(NOMBRE) = 'PORTERÍA PRINCIPAL'));
UPDATE PORTERIAS SET NOMBRE = 'Portería Principal', ESTADO = 'ACTIVA' WHERE ID_PORTERIA = 1;

-- ------------------------------------------------------------------------------
-- 4. Units (4 Core Units: Apto 101, Apto 102, Apto 201, Apto 202)
-- ------------------------------------------------------------------------------
INSERT INTO UNIDADES (ID_UNIDAD, ID_PROPIEDAD, ID_TIPO_UNIDAD, IDENTIFICADOR, AREA_M2, COEFICIENTE_COPROPIEDAD, ESTADO)
SELECT 1, 1, 1, 'Apto 101', 65.00, 0.025000, 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM UNIDADES WHERE ID_UNIDAD = 1);
UPDATE UNIDADES SET ID_PROPIEDAD = 1, IDENTIFICADOR = 'Apto 101', AREA_M2 = 65.00, COEFICIENTE_COPROPIEDAD = 0.025000, ESTADO = 'ACTIVA' WHERE ID_UNIDAD = 1;

INSERT INTO UNIDADES (ID_UNIDAD, ID_PROPIEDAD, ID_TIPO_UNIDAD, IDENTIFICADOR, AREA_M2, COEFICIENTE_COPROPIEDAD, ESTADO)
SELECT 2, 1, 1, 'Apto 102', 65.00, 0.025000, 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM UNIDADES WHERE ID_UNIDAD = 2);
UPDATE UNIDADES SET ID_PROPIEDAD = 1, IDENTIFICADOR = 'Apto 102', AREA_M2 = 65.00, COEFICIENTE_COPROPIEDAD = 0.025000, ESTADO = 'ACTIVA' WHERE ID_UNIDAD = 2;

INSERT INTO UNIDADES (ID_UNIDAD, ID_PROPIEDAD, ID_TIPO_UNIDAD, IDENTIFICADOR, AREA_M2, COEFICIENTE_COPROPIEDAD, ESTADO)
SELECT 3, 1, 1, 'Apto 201', 85.00, 0.035000, 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM UNIDADES WHERE ID_UNIDAD = 3);
UPDATE UNIDADES SET ID_PROPIEDAD = 1, IDENTIFICADOR = 'Apto 201', AREA_M2 = 85.00, COEFICIENTE_COPROPIEDAD = 0.035000, ESTADO = 'ACTIVA' WHERE ID_UNIDAD = 3;

INSERT INTO UNIDADES (ID_UNIDAD, ID_PROPIEDAD, ID_TIPO_UNIDAD, IDENTIFICADOR, AREA_M2, COEFICIENTE_COPROPIEDAD, ESTADO)
SELECT 4, 1, 1, 'Apto 202', 85.00, 0.035000, 'ACTIVA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM UNIDADES WHERE ID_UNIDAD = 4);
UPDATE UNIDADES SET ID_PROPIEDAD = 1, IDENTIFICADOR = 'Apto 202', AREA_M2 = 85.00, COEFICIENTE_COPROPIEDAD = 0.035000, ESTADO = 'ACTIVA' WHERE ID_UNIDAD = 4;

-- ------------------------------------------------------------------------------
-- 5. Personas (SuperAdmin, Admin, Portero, Residentes 1 y 2, Visitante)
-- ------------------------------------------------------------------------------
INSERT INTO PERSONAS (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, PRIMER_NOMBRE, PRIMER_APELLIDO, EMAIL)
SELECT 1, 1, '1000000001', 'NATURAL', 'Super', 'Admin', 'admin_global@saed.com' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERSONAS WHERE ID_PERSONA = 1);
UPDATE PERSONAS SET EMAIL = 'admin_global@saed.com', PRIMER_NOMBRE = 'Super', PRIMER_APELLIDO = 'Admin' WHERE ID_PERSONA = 1;

INSERT INTO PERSONAS (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, PRIMER_NOMBRE, PRIMER_APELLIDO, EMAIL)
SELECT 2, 1, '1000000002', 'NATURAL', 'Admin', 'Propiedad', 'admin@saed.com' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERSONAS WHERE ID_PERSONA = 2);
UPDATE PERSONAS SET EMAIL = 'admin@saed.com', PRIMER_NOMBRE = 'Admin', PRIMER_APELLIDO = 'Propiedad' WHERE ID_PERSONA = 2;

INSERT INTO PERSONAS (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, PRIMER_NOMBRE, PRIMER_APELLIDO, EMAIL)
SELECT 3, 1, '1000000003', 'NATURAL', 'Portero', 'Principal', 'portero01@saed.com' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERSONAS WHERE ID_PERSONA = 3);
UPDATE PERSONAS SET EMAIL = 'portero01@saed.com', PRIMER_NOMBRE = 'Portero', PRIMER_APELLIDO = 'Principal' WHERE ID_PERSONA = 3;

INSERT INTO PERSONAS (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, PRIMER_NOMBRE, PRIMER_APELLIDO, EMAIL)
SELECT 4, 1, '1000000004', 'NATURAL', 'Carlos', 'Martinez', 'camartinez@saed.com' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERSONAS WHERE ID_PERSONA = 4);
UPDATE PERSONAS SET EMAIL = 'camartinez@saed.com', PRIMER_NOMBRE = 'Carlos', PRIMER_APELLIDO = 'Martinez' WHERE ID_PERSONA = 4;

INSERT INTO PERSONAS (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, PRIMER_NOMBRE, PRIMER_APELLIDO, EMAIL)
SELECT 5, 1, '1000000005', 'NATURAL', 'Ana', 'Gomez', 'anagomez@saed.com' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERSONAS WHERE ID_PERSONA = 5);
UPDATE PERSONAS SET EMAIL = 'anagomez@saed.com', PRIMER_NOMBRE = 'Ana', PRIMER_APELLIDO = 'Gomez' WHERE ID_PERSONA = 5;

INSERT INTO PERSONAS (ID_PERSONA, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TIPO_PERSONA, PRIMER_NOMBRE, PRIMER_APELLIDO, EMAIL)
SELECT 10, 1, '1000000010', 'NATURAL', 'Visitante', 'Demo', 'visitante.demo@saed.com' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERSONAS WHERE ID_PERSONA = 10);
UPDATE PERSONAS SET EMAIL = 'visitante.demo@saed.com', PRIMER_NOMBRE = 'Visitante', PRIMER_APELLIDO = 'Demo' WHERE ID_PERSONA = 10;

-- ------------------------------------------------------------------------------
-- 6. Usuarios (Passwords: admin_global -> admin_global123 | others -> admin123)
-- Hash BCrypt: $2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3
-- ------------------------------------------------------------------------------
INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, NOMBRE_USUARIO, EMAIL, HASH_PASSWORD, ESTADO, INTENTOS_FALLIDOS)
SELECT 1, 1, 'admin_global', 'admin_global@saed.com', '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', 'ACTIVO', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = 1);
UPDATE USUARIOS SET NOMBRE_USUARIO = 'admin_global', EMAIL = 'admin_global@saed.com', HASH_PASSWORD = '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', ESTADO = 'ACTIVO', INTENTOS_FALLIDOS = 0 WHERE ID_USUARIO = 1;

INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, NOMBRE_USUARIO, EMAIL, HASH_PASSWORD, ESTADO, INTENTOS_FALLIDOS)
SELECT 2, 2, 'admin', 'admin@saed.com', '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', 'ACTIVO', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = 2);
UPDATE USUARIOS SET NOMBRE_USUARIO = 'admin', EMAIL = 'admin@saed.com', HASH_PASSWORD = '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', ESTADO = 'ACTIVO', INTENTOS_FALLIDOS = 0 WHERE ID_USUARIO = 2;

INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, NOMBRE_USUARIO, EMAIL, HASH_PASSWORD, ESTADO, INTENTOS_FALLIDOS)
SELECT 3, 3, 'portero01', 'portero01@saed.com', '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', 'ACTIVO', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = 3);
UPDATE USUARIOS SET NOMBRE_USUARIO = 'portero01', EMAIL = 'portero01@saed.com', HASH_PASSWORD = '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', ESTADO = 'ACTIVO', INTENTOS_FALLIDOS = 0 WHERE ID_USUARIO = 3;

INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, NOMBRE_USUARIO, EMAIL, HASH_PASSWORD, ESTADO, INTENTOS_FALLIDOS)
SELECT 4, 4, 'camartinez', 'camartinez@saed.com', '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', 'ACTIVO', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = 4);
UPDATE USUARIOS SET NOMBRE_USUARIO = 'camartinez', EMAIL = 'camartinez@saed.com', HASH_PASSWORD = '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', ESTADO = 'ACTIVO', INTENTOS_FALLIDOS = 0 WHERE ID_USUARIO = 4;

INSERT INTO USUARIOS (ID_USUARIO, ID_PERSONA, NOMBRE_USUARIO, EMAIL, HASH_PASSWORD, ESTADO, INTENTOS_FALLIDOS)
SELECT 5, 5, 'anagomez', 'anagomez@saed.com', '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', 'ACTIVO', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = 5);
UPDATE USUARIOS SET NOMBRE_USUARIO = 'anagomez', EMAIL = 'anagomez@saed.com', HASH_PASSWORD = '$2a$10$Y8yWwG2uR38jM8eIq0f6oOV3/1vM7Z13GkIefw7U9M/P0FqX3q4P3', ESTADO = 'ACTIVO', INTENTOS_FALLIDOS = 0 WHERE ID_USUARIO = 5;

-- ------------------------------------------------------------------------------
-- 7. SuperAdmin Record (ADMINISTRADORES_SAED)
-- ------------------------------------------------------------------------------
INSERT INTO ADMINISTRADORES_SAED (ID_ADMINISTRADOR_SAED, ID_USUARIO, NIVEL, ESTADO)
SELECT 1, 1, 'SUPERADMIN', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMINISTRADORES_SAED WHERE ID_USUARIO = 1);
UPDATE ADMINISTRADORES_SAED SET NIVEL = 'SUPERADMIN', ESTADO = 'ACTIVO' WHERE ID_USUARIO = 1;

-- ------------------------------------------------------------------------------
-- 8. User Role Assignments (Strict TRG_ASIGNACION_VALIDA_SCOPE compliance)
-- ------------------------------------------------------------------------------
DELETE FROM USUARIO_ASIGNACIONES WHERE ID_USUARIO IN (1, 2, 3, 4, 5) AND ID_ASIGNACION NOT IN (101, 102, 103, 104, 105);

-- 101: SuperAdmin (GLOBAL -> NO org, NO prop, NO unidad)
INSERT INTO USUARIO_ASIGNACIONES (ID_ASIGNACION, ID_USUARIO, ID_ROL, ESTADO, FECHA_INICIO)
SELECT 101, 1, (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'SUPERADMIN'), 'ACTIVA', TRUNC(SYSDATE) FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIO_ASIGNACIONES WHERE ID_ASIGNACION = 101 OR (ID_USUARIO = 1 AND ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'SUPERADMIN')));
UPDATE USUARIO_ASIGNACIONES SET ID_USUARIO = 1, ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'SUPERADMIN'), ID_ORGANIZACION = NULL, ID_PROPIEDAD = NULL, ID_UNIDAD = NULL, ESTADO = 'ACTIVA' WHERE ID_ASIGNACION = 101;

-- 102: Admin Propiedad (PROPIEDAD -> Org 1, Prop 1, NO unidad)
INSERT INTO USUARIO_ASIGNACIONES (ID_ASIGNACION, ID_USUARIO, ID_ROL, ID_ORGANIZACION, ID_PROPIEDAD, ESTADO, FECHA_INICIO)
SELECT 102, 2, (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'ADMIN_PROPIEDAD'), 1, 1, 'ACTIVA', TRUNC(SYSDATE) FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIO_ASIGNACIONES WHERE ID_ASIGNACION = 102 OR (ID_USUARIO = 2 AND ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'ADMIN_PROPIEDAD')));
UPDATE USUARIO_ASIGNACIONES SET ID_USUARIO = 2, ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'ADMIN_PROPIEDAD'), ID_ORGANIZACION = 1, ID_PROPIEDAD = 1, ID_UNIDAD = NULL, ESTADO = 'ACTIVA' WHERE ID_ASIGNACION = 102;

-- 103: Portero (PROPIEDAD -> Org 1, Prop 1, NO unidad)
INSERT INTO USUARIO_ASIGNACIONES (ID_ASIGNACION, ID_USUARIO, ID_ROL, ID_ORGANIZACION, ID_PROPIEDAD, ESTADO, FECHA_INICIO)
SELECT 103, 3, (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'PORTERO'), 1, 1, 'ACTIVA', TRUNC(SYSDATE) FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIO_ASIGNACIONES WHERE ID_ASIGNACION = 103 OR (ID_USUARIO = 3 AND ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'PORTERO')));
UPDATE USUARIO_ASIGNACIONES SET ID_USUARIO = 3, ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'PORTERO'), ID_ORGANIZACION = 1, ID_PROPIEDAD = 1, ID_UNIDAD = NULL, ESTADO = 'ACTIVA' WHERE ID_ASIGNACION = 103;

-- 104: Residente 1 (UNIDAD -> Org 1, Prop 1, Unidad 1 / Apto 101)
INSERT INTO USUARIO_ASIGNACIONES (ID_ASIGNACION, ID_USUARIO, ID_ROL, ID_ORGANIZACION, ID_PROPIEDAD, ID_UNIDAD, ESTADO, FECHA_INICIO)
SELECT 104, 4, (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'RESIDENTE'), 1, 1, 1, 'ACTIVA', TRUNC(SYSDATE) FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIO_ASIGNACIONES WHERE ID_ASIGNACION = 104 OR (ID_USUARIO = 4 AND ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'RESIDENTE')));
UPDATE USUARIO_ASIGNACIONES SET ID_USUARIO = 4, ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'RESIDENTE'), ID_ORGANIZACION = 1, ID_PROPIEDAD = 1, ID_UNIDAD = 1, ESTADO = 'ACTIVA' WHERE ID_ASIGNACION = 104;

-- 105: Residente 2 (UNIDAD -> Org 1, Prop 1, Unidad 2 / Apto 102)
INSERT INTO USUARIO_ASIGNACIONES (ID_ASIGNACION, ID_USUARIO, ID_ROL, ID_ORGANIZACION, ID_PROPIEDAD, ID_UNIDAD, ESTADO, FECHA_INICIO)
SELECT 105, 5, (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'RESIDENTE'), 1, 1, 2, 'ACTIVA', TRUNC(SYSDATE) FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USUARIO_ASIGNACIONES WHERE ID_ASIGNACION = 105 OR (ID_USUARIO = 5 AND ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'RESIDENTE')));
UPDATE USUARIO_ASIGNACIONES SET ID_USUARIO = 5, ID_ROL = (SELECT ID_ROL FROM ROLES WHERE CODIGO = 'RESIDENTE'), ID_ORGANIZACION = 1, ID_PROPIEDAD = 1, ID_UNIDAD = 2, ESTADO = 'ACTIVA' WHERE ID_ASIGNACION = 105;

-- ------------------------------------------------------------------------------
-- 9. Residents Linkage (RESIDENTES_UNIDAD)
-- ------------------------------------------------------------------------------
INSERT INTO RESIDENTES_UNIDAD (ID_UNIDAD, ID_PERSONA, TIPO_RESIDENTE, FECHA_INICIO, ESTADO)
SELECT 1, 4, 'PROPIETARIO', TRUNC(SYSDATE), 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RESIDENTES_UNIDAD WHERE ID_UNIDAD = 1 AND ID_PERSONA = 4);
UPDATE RESIDENTES_UNIDAD SET TIPO_RESIDENTE = 'PROPIETARIO', ESTADO = 'ACTIVO' WHERE ID_UNIDAD = 1 AND ID_PERSONA = 4;

INSERT INTO RESIDENTES_UNIDAD (ID_UNIDAD, ID_PERSONA, TIPO_RESIDENTE, FECHA_INICIO, ESTADO)
SELECT 2, 5, 'ARRENDATARIO', TRUNC(SYSDATE), 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RESIDENTES_UNIDAD WHERE ID_UNIDAD = 2 AND ID_PERSONA = 5);
UPDATE RESIDENTES_UNIDAD SET TIPO_RESIDENTE = 'ARRENDATARIO', ESTADO = 'ACTIVO' WHERE ID_UNIDAD = 2 AND ID_PERSONA = 5;

-- ------------------------------------------------------------------------------
-- 10. Visitor & Scheduled Visit with QR Access
-- ------------------------------------------------------------------------------
INSERT INTO VISITANTES (ID_VISITANTE, ID_PERSONA, ES_FRECUENTE, EMPRESA, ESTADO)
SELECT 10, 10, 'S', 'Logistica Demo', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM VISITANTES WHERE ID_PERSONA = 10);
UPDATE VISITANTES SET ES_FRECUENTE = 'S', EMPRESA = 'Logistica Demo', ESTADO = 'ACTIVO' WHERE ID_PERSONA = 10;

INSERT INTO VISITAS (ID_VISITA, ID_UNIDAD, ID_VISITANTE, METODO_INGRESO, MOTIVO, AUTORIZADO_POR, FECHA_PROGRAMADA, ESTADO)
SELECT 100, 1, (SELECT MIN(ID_VISITANTE) FROM VISITANTES WHERE ID_PERSONA = 10), 'CODIGO_QR', 'Demostracion Visita Funcional', 4, CURRENT_TIMESTAMP + INTERVAL '1' DAY, 'PROGRAMADA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM VISITAS WHERE ID_VISITA = 100);
UPDATE VISITAS SET METODO_INGRESO = 'CODIGO_QR', MOTIVO = 'Demostracion Visita Funcional', ESTADO = 'PROGRAMADA' WHERE ID_VISITA = 100;

INSERT INTO QR_ACCESOS (ID_QR, ID_VISITA, TOKEN_QR, FECHA_EXPIRACION, USOS_PERMITIDOS, USOS_CONSUMIDOS, ESTADO)
SELECT 100, 100, 'SAED-DEMO-QR-2026-TOKEN', CURRENT_TIMESTAMP + INTERVAL '2' DAY, 5, 0, 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM QR_ACCESOS WHERE ID_QR = 100 OR TOKEN_QR = 'SAED-DEMO-QR-2026-TOKEN');
UPDATE QR_ACCESOS SET ID_VISITA = 100, FECHA_EXPIRACION = CURRENT_TIMESTAMP + INTERVAL '2' DAY, ESTADO = 'ACTIVO', USOS_CONSUMIDOS = 0 WHERE TOKEN_QR = 'SAED-DEMO-QR-2026-TOKEN';

-- ------------------------------------------------------------------------------
-- 11. Parking & Visitor Vehicle Association
-- ------------------------------------------------------------------------------
INSERT INTO PARQUEADEROS (ID_PARQUEADERO, ID_PROPIEDAD, NUMERO_PARQUEADERO, TIPO, ESTADO)
SELECT 1, 1, 'V-01', 'VISITANTES', 'DISPONIBLE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PARQUEADEROS WHERE ID_PARQUEADERO = 1 OR (ID_PROPIEDAD = 1 AND UPPER(NUMERO_PARQUEADERO) = 'V-01'));
UPDATE PARQUEADEROS SET NUMERO_PARQUEADERO = 'V-01', TIPO = 'VISITANTES', ESTADO = 'DISPONIBLE' WHERE ID_PARQUEADERO = 1;

INSERT INTO PARQUEADEROS (ID_PARQUEADERO, ID_PROPIEDAD, NUMERO_PARQUEADERO, TIPO, ESTADO)
SELECT 2, 1, 'V-02', 'VISITANTES', 'DISPONIBLE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PARQUEADEROS WHERE ID_PARQUEADERO = 2 OR (ID_PROPIEDAD = 1 AND UPPER(NUMERO_PARQUEADERO) = 'V-02'));
UPDATE PARQUEADEROS SET NUMERO_PARQUEADERO = 'V-02', TIPO = 'VISITANTES', ESTADO = 'DISPONIBLE' WHERE ID_PARQUEADERO = 2;

INSERT INTO PARQUEADEROS (ID_PARQUEADERO, ID_PROPIEDAD, NUMERO_PARQUEADERO, TIPO, ESTADO)
SELECT 3, 1, 'P-101', 'PRIVADO', 'DISPONIBLE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PARQUEADEROS WHERE ID_PARQUEADERO = 3 OR (ID_PROPIEDAD = 1 AND UPPER(NUMERO_PARQUEADERO) = 'P-101'));
UPDATE PARQUEADEROS SET NUMERO_PARQUEADERO = 'P-101', TIPO = 'PRIVADO', ESTADO = 'DISPONIBLE' WHERE ID_PARQUEADERO = 3;

INSERT INTO VEHICULOS_VISITA (ID_VEHICULO_VISITA, ID_VISITA, ID_PARQUEADERO, PLACA, TIPO_VEHICULO, FECHA_INGRESO, COSTO_TOTAL, ESTADO)
SELECT 1, 100, 1, 'DEM-123', 'AUTOMOVIL', CURRENT_TIMESTAMP, 0, 'DENTRO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM VEHICULOS_VISITA WHERE ID_VEHICULO_VISITA = 1);
UPDATE VEHICULOS_VISITA SET PLACA = 'DEM-123', ESTADO = 'DENTRO' WHERE ID_VEHICULO_VISITA = 1;

INSERT INTO REGISTROS_ACCESO (ID_REGISTRO_ACCESO, ID_PROPIEDAD, ID_PORTERIA, ID_VISITA, ID_PERSONA, ID_UNIDAD, ID_QR, TIPO_MOVIMIENTO, METODO_AUTORIZACION, FECHA_HORA, PORTERO_OPERADOR, PLACA_VEHICULO, OBSERVACIONES)
SELECT 1, 1, 1, 100, 10, 1, 100, 'ENTRADA', 'QR_SCAN', CURRENT_TIMESTAMP - INTERVAL '1' HOUR, 3, 'DEM-123', 'CARRO - Ingreso vehículo demo' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM REGISTROS_ACCESO WHERE ID_REGISTRO_ACCESO = 1);
UPDATE REGISTROS_ACCESO SET PLACA_VEHICULO = 'DEM-123', TIPO_MOVIMIENTO = 'ENTRADA' WHERE ID_REGISTRO_ACCESO = 1;

-- ------------------------------------------------------------------------------
-- 12. Financial Concepts & Contracts
-- ------------------------------------------------------------------------------
INSERT INTO CONCEPTOS_COBRO (ID_CONCEPTO, ID_ORGANIZACION, ID_PROPIEDAD, CODIGO, NOMBRE, TIPO, APLICA_MORA, ESTADO)
SELECT 1, 1, 1, 'CUOTA_ADMIN', 'Cuota de Administracion', 'ADMINISTRACION', 'S', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONCEPTOS_COBRO WHERE ID_CONCEPTO = 1 OR (ID_ORGANIZACION = 1 AND ID_PROPIEDAD = 1 AND CODIGO = 'CUOTA_ADMIN'));
UPDATE CONCEPTOS_COBRO SET NOMBRE = 'Cuota de Administracion', ESTADO = 'ACTIVO' WHERE ID_CONCEPTO = 1;

INSERT INTO CONTRATOS (ID_CONTRATO, ID_UNIDAD, ID_ARRENDATARIO_PRINCIPAL, NUMERO_CONTRATO, CANON_MENSUAL, DIA_CORTE_PAGO, FECHA_INICIO, FECHA_FIN, TIPO_CONTRATO, ESTADO)
SELECT 1, 1, 4, 'CNT-2026-001', 250000.00, 5, DATE '2026-01-01', DATE '2026-12-31', 'INICIAL', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONTRATOS WHERE ID_CONTRATO = 1 OR (ID_UNIDAD = 1 AND ESTADO = 'ACTIVO'));
UPDATE CONTRATOS SET CANON_MENSUAL = 250000.00, ESTADO = 'ACTIVO' WHERE ID_CONTRATO = 1;

INSERT INTO CONTRATOS (ID_CONTRATO, ID_UNIDAD, ID_ARRENDATARIO_PRINCIPAL, NUMERO_CONTRATO, CANON_MENSUAL, DIA_CORTE_PAGO, FECHA_INICIO, FECHA_FIN, TIPO_CONTRATO, ESTADO)
SELECT 2, 2, 5, 'CNT-2026-002', 250000.00, 5, DATE '2026-01-01', DATE '2026-12-31', 'INICIAL', 'ACTIVO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CONTRATOS WHERE ID_CONTRATO = 2 OR (ID_UNIDAD = 2 AND ESTADO = 'ACTIVO'));
UPDATE CONTRATOS SET CANON_MENSUAL = 250000.00, ESTADO = 'ACTIVO' WHERE ID_CONTRATO = 2;

-- ------------------------------------------------------------------------------
-- 13. Financial Ledger: Cuotas & Pagos
--     - Unit 1: 1 PAGADA (Ago 2026), 1 PENDIENTE (Sep 2026) -> Saldo pendiente $250,000
--     - Unit 2: 1 PAGADA (Sep 2026) -> Saldo pendiente $0
-- ------------------------------------------------------------------------------
-- Cuota 1 (Apto 101, Periodo 2026-08 - PAGADA)
INSERT INTO CUOTAS (ID_CUOTA, ID_UNIDAD, ID_CONCEPTO, ID_CONTRATO, PERIODO, VALOR_BASE, VALOR_DESCUENTO, VALOR_INTERES_MORA, SALDO_PENDIENTE, FECHA_EMISION, FECHA_VENCIMIENTO, ESTADO, DESCRIPCION)
SELECT 1, 1, 1, 1, '2026-08', 250000.00, 0, 0, 0.00, DATE '2026-08-01', DATE '2026-08-15', 'PAGADA', 'Cuota Administracion Agosto 2026' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUOTAS WHERE ID_CUOTA = 1 OR (ID_UNIDAD = 1 AND ID_CONCEPTO = 1 AND PERIODO = '2026-08'));
UPDATE CUOTAS SET SALDO_PENDIENTE = 0.00, ESTADO = 'PAGADA' WHERE ID_CUOTA = 1;

-- Cuota 2 (Apto 101, Periodo 2026-09 - PENDIENTE)
INSERT INTO CUOTAS (ID_CUOTA, ID_UNIDAD, ID_CONCEPTO, ID_CONTRATO, PERIODO, VALOR_BASE, VALOR_DESCUENTO, VALOR_INTERES_MORA, SALDO_PENDIENTE, FECHA_EMISION, FECHA_VENCIMIENTO, ESTADO, DESCRIPCION)
SELECT 2, 1, 1, 1, '2026-09', 250000.00, 0, 0, 250000.00, DATE '2026-09-01', DATE '2026-09-15', 'PENDIENTE', 'Cuota Administracion Septiembre 2026' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUOTAS WHERE ID_CUOTA = 2 OR (ID_UNIDAD = 1 AND ID_CONCEPTO = 1 AND PERIODO = '2026-09'));
UPDATE CUOTAS SET SALDO_PENDIENTE = 250000.00, ESTADO = 'PENDIENTE' WHERE ID_CUOTA = 2;

-- Cuota 3 (Apto 102, Periodo 2026-09 - PAGADA)
INSERT INTO CUOTAS (ID_CUOTA, ID_UNIDAD, ID_CONCEPTO, ID_CONTRATO, PERIODO, VALOR_BASE, VALOR_DESCUENTO, VALOR_INTERES_MORA, SALDO_PENDIENTE, FECHA_EMISION, FECHA_VENCIMIENTO, ESTADO, DESCRIPCION)
SELECT 3, 2, 1, 2, '2026-09', 250000.00, 0, 0, 0.00, DATE '2026-09-01', DATE '2026-09-15', 'PAGADA', 'Cuota Administracion Septiembre 2026' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUOTAS WHERE ID_CUOTA = 3 OR (ID_UNIDAD = 2 AND ID_CONCEPTO = 1 AND PERIODO = '2026-09'));
UPDATE CUOTAS SET SALDO_PENDIENTE = 0.00, ESTADO = 'PAGADA' WHERE ID_CUOTA = 3;

-- Pago 1 (Aplicado a Cuota 1 de Apto 101)
INSERT INTO PAGOS (ID_PAGO, ID_UNIDAD, ID_PERSONA_PAGA, MONTO_TOTAL, METODO_PAGO, REFERENCIA_COMPROBANTE, IDEMPOTENCY_KEY, ESTADO, APROBADO_POR, FECHA_APROBACION, OBSERVACIONES)
SELECT 1, 1, 4, 250000.00, 'TRANSFERENCIA', 'TRF-DEMO-001', 'IDEMP-PAGO-001-DEMO', 'APROBADO', 2, CURRENT_TIMESTAMP, 'Pago cuota agosto verificado en demostracion' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PAGOS WHERE ID_PAGO = 1 OR IDEMPOTENCY_KEY = 'IDEMP-PAGO-001-DEMO');
UPDATE PAGOS SET MONTO_TOTAL = 250000.00, ESTADO = 'APROBADO' WHERE ID_PAGO = 1;

INSERT INTO PAGO_DETALLE (ID_PAGO_DETALLE, ID_PAGO, ID_CUOTA, MONTO_APLICADO)
SELECT 1, 1, 1, 250000.00 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PAGO_DETALLE WHERE ID_PAGO_DETALLE = 1 OR (ID_PAGO = 1 AND ID_CUOTA = 1));
UPDATE PAGO_DETALLE SET MONTO_APLICADO = 250000.00 WHERE ID_PAGO_DETALLE = 1;

-- Pago 2 (Aplicado a Cuota 3 de Apto 102)
INSERT INTO PAGOS (ID_PAGO, ID_UNIDAD, ID_PERSONA_PAGA, MONTO_TOTAL, METODO_PAGO, REFERENCIA_COMPROBANTE, IDEMPOTENCY_KEY, ESTADO, APROBADO_POR, FECHA_APROBACION, OBSERVACIONES)
SELECT 2, 2, 5, 250000.00, 'PASARELA_WOMPI', 'WOMPI-TX-998877', 'IDEMP-PAGO-002-DEMO', 'APROBADO', 2, CURRENT_TIMESTAMP, 'Pago en linea Wompi aprobado' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PAGOS WHERE ID_PAGO = 2 OR IDEMPOTENCY_KEY = 'IDEMP-PAGO-002-DEMO');
UPDATE PAGOS SET MONTO_TOTAL = 250000.00, ESTADO = 'APROBADO' WHERE ID_PAGO = 2;

INSERT INTO PAGO_DETALLE (ID_PAGO_DETALLE, ID_PAGO, ID_CUOTA, MONTO_APLICADO)
SELECT 2, 2, 3, 250000.00 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PAGO_DETALLE WHERE ID_PAGO_DETALLE = 2 OR (ID_PAGO = 2 AND ID_CUOTA = 3));
UPDATE PAGO_DETALLE SET MONTO_APLICADO = 250000.00 WHERE ID_PAGO_DETALLE = 2;

-- ------------------------------------------------------------------------------
-- 13b. Cartera: Initial Unit Balances
--      Ensure virtual column SALDO_TOTAL is correct formula and units 1..4 seeded
-- ------------------------------------------------------------------------------
/
BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARTERA DROP COLUMN SALDO_TOTAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARTERA ADD SALDO_TOTAL AS (SALDO_CORRIENTE + SALDO_MORA_30 + SALDO_MORA_60 + SALDO_MORA_90_MAS)'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

INSERT INTO CARTERA (ID_CARTERA, ID_UNIDAD, SALDO_CORRIENTE, SALDO_MORA_30, SALDO_MORA_60, SALDO_MORA_90_MAS, FECHA_CORTE, ESTADO_CARTERA)
SELECT 1, 1, 250000.00, 0, 0, 0, TRUNC(SYSDATE), 'AL_DIA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CARTERA WHERE ID_CARTERA = 1 OR ID_UNIDAD = 1);
UPDATE CARTERA SET SALDO_CORRIENTE = 250000.00, SALDO_MORA_30 = 0, SALDO_MORA_60 = 0, SALDO_MORA_90_MAS = 0, ESTADO_CARTERA = 'AL_DIA', FECHA_CORTE = TRUNC(SYSDATE) WHERE ID_UNIDAD = 1;

INSERT INTO CARTERA (ID_CARTERA, ID_UNIDAD, SALDO_CORRIENTE, SALDO_MORA_30, SALDO_MORA_60, SALDO_MORA_90_MAS, FECHA_CORTE, ESTADO_CARTERA)
SELECT 2, 2, 0.00, 0, 0, 0, TRUNC(SYSDATE), 'AL_DIA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CARTERA WHERE ID_CARTERA = 2 OR ID_UNIDAD = 2);
UPDATE CARTERA SET SALDO_CORRIENTE = 0.00, SALDO_MORA_30 = 0, SALDO_MORA_60 = 0, SALDO_MORA_90_MAS = 0, ESTADO_CARTERA = 'AL_DIA', FECHA_CORTE = TRUNC(SYSDATE) WHERE ID_UNIDAD = 2;

INSERT INTO CARTERA (ID_CARTERA, ID_UNIDAD, SALDO_CORRIENTE, SALDO_MORA_30, SALDO_MORA_60, SALDO_MORA_90_MAS, FECHA_CORTE, ESTADO_CARTERA)
SELECT 3, 3, 0.00, 0, 0, 0, TRUNC(SYSDATE), 'AL_DIA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CARTERA WHERE ID_CARTERA = 3 OR ID_UNIDAD = 3);
UPDATE CARTERA SET SALDO_CORRIENTE = 0.00, SALDO_MORA_30 = 0, SALDO_MORA_60 = 0, SALDO_MORA_90_MAS = 0, ESTADO_CARTERA = 'AL_DIA', FECHA_CORTE = TRUNC(SYSDATE) WHERE ID_UNIDAD = 3;

INSERT INTO CARTERA (ID_CARTERA, ID_UNIDAD, SALDO_CORRIENTE, SALDO_MORA_30, SALDO_MORA_60, SALDO_MORA_90_MAS, FECHA_CORTE, ESTADO_CARTERA)
SELECT 4, 4, 0.00, 0, 0, 0, TRUNC(SYSDATE), 'AL_DIA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CARTERA WHERE ID_CARTERA = 4 OR ID_UNIDAD = 4);
UPDATE CARTERA SET SALDO_CORRIENTE = 0.00, SALDO_MORA_30 = 0, SALDO_MORA_60 = 0, SALDO_MORA_90_MAS = 0, ESTADO_CARTERA = 'AL_DIA', FECHA_CORTE = TRUNC(SYSDATE) WHERE ID_UNIDAD = 4;

-- ------------------------------------------------------------------------------
-- 13c. Official Communications (COMUNICADOS)
-- ------------------------------------------------------------------------------
INSERT INTO COMUNICADOS (ID_COMUNICADO, ID_PROPIEDAD, TITULO, CONTENIDO, TIPO_SEGMENTACION, PRIORIDAD, REQUIERE_CONFIRMACION, FECHA_PUBLICACION, ESTADO)
SELECT 1, 1, 'Comunicado General SAED', 'Bienvenido al sistema de administración y control de acceso SAED 2.0.', 'TODOS', 'NORMAL', 'N', CURRENT_TIMESTAMP, 'PUBLICADO' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMUNICADOS WHERE ID_COMUNICADO = 1);
UPDATE COMUNICADOS SET ID_PROPIEDAD = 1, TITULO = 'Comunicado General SAED', PRIORIDAD = 'NORMAL', ESTADO = 'PUBLICADO' WHERE ID_COMUNICADO = 1;

-- ------------------------------------------------------------------------------
-- 14. Adjust IDENTITY column values to avoid sequence collisions
-- ------------------------------------------------------------------------------
/
BEGIN
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PERSONAS MODIFY (ID_PERSONA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USUARIOS MODIFY (ID_USUARIO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USUARIO_ASIGNACIONES MODIFY (ID_ASIGNACION GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE UNIDADES MODIFY (ID_UNIDAD GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PARQUEADEROS MODIFY (ID_PARQUEADERO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CUOTAS MODIFY (ID_CUOTA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAGOS MODIFY (ID_PAGO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAGO_DETALLE MODIFY (ID_PAGO_DETALLE GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARTERA MODIFY (ID_CARTERA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE VISITAS MODIFY (ID_VISITA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE VISITANTES MODIFY (ID_VISITANTE GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE QR_ACCESOS MODIFY (ID_QR GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE VEHICULOS_VISITA MODIFY (ID_VEHICULO_VISITA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PORTERIAS MODIFY (ID_PORTERIA GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAQUETES MODIFY (ID_PAQUETE GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE COMUNICADOS MODIFY (ID_COMUNICADO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'ALTER TABLE REGISTROS_ACCESO MODIFY (ID_REGISTRO_ACCESO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))'; EXCEPTION WHEN OTHERS THEN NULL; END;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- ------------------------------------------------------------------------------
-- 15. Clear Context & Commit
-- ------------------------------------------------------------------------------
BEGIN
    PKG_SAED_SESSION.CLEAR_CONTEXT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

COMMIT;
